### ISSUE TITLE
Document required LLVM/Clang version

### ISSUE THREAD

**Issue by CruzR** [BearishSun/BansheeSBGen#1]
Hi there,

I'm trying to build this, but unfortunately it does not specify which version of LLVM & Clang is required. Since building LLVM/Clang takes quite a bit of time, and therefore trial and error is not really a satisfying option, it would be helpful if the README documented which version to use.

**Comment by BearishSun** [comment]
Hi, the project was just updated so it compiles with Clang 5.0.0. and version is now stated in the README.
