### ISSUE TITLE
Linux support will be a bear to implement ( pardon the pun :P )

### ISSUE THREAD

**Issue by nemerle** [BearishSun/BansheeSBGen#3]
According to clang faq:

> Some header files (stddef.h, stdarg.h, and others) are shipped with Clang — these are called builtin includes. Clang searches for them in a directory relative to the location of the clang binary. If you moved the clang binary, you need to move the builtin headers, too.

So when BansheeSBGen is run, at least on linux, it tries to locate the missing headers using relative paths as it assumes it lives in the same directory as clang executable, thus it adds something like ../lib/clang/VERSION/include/ as it resource_dir.
One possible solution would be to somehow extract the clang location and feed an additional argument to BansheeSBGen:
```-Xclang -resource-dir -Xclang /absolute_path_to/lib/clang/VERSION/include/```  ?

**Comment by nemerle** [comment]
The following command (assuming foo.c at least exists ) is able to extract the resource path:
```bash
clang++ '-###' -c foo.c 2>&1 | tr ' ' '\n' | grep -A1 resource
```
The result I've got here is:
```
"-resource-dir"
"/usr/lib/clang/5.0.0"
```

**Comment by BearishSun** [comment]
I encountered this issue and the problem is solved by copying the builtin includes in a folder relative to the SBGen binary. This does not require the user to have clang installed.

**Comment by nemerle** [comment]
True, would be great that copying was an install step of BansheeSBGen ?

**Comment by BearishSun** [comment]
Indeed, I plan on integrating it into the build process eventually, but haven't gotten around to it yet.

**Comment by nemerle** [comment]
Great, if You don't mind, please leave this issue open, I might find some time to try and cobble something together that will do that.

**Comment by BearishSun** [comment]
Sure

**Comment by BearishSun** [comment]
I've added an install step that will automatically copy the include folder. Note that Banshee itself hasn't been updated with the new search paths, so it will be unable to find the SBGen until I push those changes (which should be in a few days).
